/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client

import java.text.SimpleDateFormat

import com.kodfarki.subscreasy.client.model.BankAccount
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class BankAccountResourceApi(
  val defBasePath: String = "https://localhost:8080",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new BankAccountResourceApiAsyncHelper(client, config)

  /**
   * createBankAccount
   * 
   *
   * @param bankAccount bankAccount 
   * @return BankAccount
   */
  def createBankAccountUsingPOST(bankAccount: BankAccount): Option[BankAccount] = {
    val await = Try(Await.result(createBankAccountUsingPOSTAsync(bankAccount), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * createBankAccount asynchronously
   * 
   *
   * @param bankAccount bankAccount 
   * @return Future(BankAccount)
   */
  def createBankAccountUsingPOSTAsync(bankAccount: BankAccount): Future[BankAccount] = {
      helper.createBankAccountUsingPOST(bankAccount)
  }

  /**
   * deleteBankAccount
   * 
   *
   * @param id id 
   * @return void
   */
  def deleteBankAccountUsingDELETE(id: Long) = {
    val await = Try(Await.result(deleteBankAccountUsingDELETEAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * deleteBankAccount asynchronously
   * 
   *
   * @param id id 
   * @return Future(void)
   */
  def deleteBankAccountUsingDELETEAsync(id: Long) = {
      helper.deleteBankAccountUsingDELETE(id)
  }

  /**
   * getAllBankAccounts
   * 
   *
   * @return List[BankAccount]
   */
  def getAllBankAccountsUsingGET(): Option[List[BankAccount]] = {
    val await = Try(Await.result(getAllBankAccountsUsingGETAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getAllBankAccounts asynchronously
   * 
   *
   * @return Future(List[BankAccount])
   */
  def getAllBankAccountsUsingGETAsync(): Future[List[BankAccount]] = {
      helper.getAllBankAccountsUsingGET()
  }

  /**
   * getBankAccount
   * 
   *
   * @param id id 
   * @return BankAccount
   */
  def getBankAccountUsingGET(id: Long): Option[BankAccount] = {
    val await = Try(Await.result(getBankAccountUsingGETAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getBankAccount asynchronously
   * 
   *
   * @param id id 
   * @return Future(BankAccount)
   */
  def getBankAccountUsingGETAsync(id: Long): Future[BankAccount] = {
      helper.getBankAccountUsingGET(id)
  }

  /**
   * updateBankAccount
   * 
   *
   * @param bankAccount bankAccount 
   * @return BankAccount
   */
  def updateBankAccountUsingPUT(bankAccount: BankAccount): Option[BankAccount] = {
    val await = Try(Await.result(updateBankAccountUsingPUTAsync(bankAccount), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * updateBankAccount asynchronously
   * 
   *
   * @param bankAccount bankAccount 
   * @return Future(BankAccount)
   */
  def updateBankAccountUsingPUTAsync(bankAccount: BankAccount): Future[BankAccount] = {
      helper.updateBankAccountUsingPUT(bankAccount)
  }

}

class BankAccountResourceApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def createBankAccountUsingPOST(bankAccount: BankAccount)(implicit reader: ClientResponseReader[BankAccount], writer: RequestWriter[BankAccount]): Future[BankAccount] = {
    // create path and map variables
    val path = (addFmt("/api/bank-accounts"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (bankAccount == null) throw new Exception("Missing required parameter 'bankAccount' when calling BankAccountResourceApi->createBankAccountUsingPOST")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(bankAccount))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def deleteBankAccountUsingDELETE(id: Long)(implicit reader: ClientResponseReader[Unit]): Future[Unit] = {
    // create path and map variables
    val path = (addFmt("/api/bank-accounts/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("DELETE", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getAllBankAccountsUsingGET()(implicit reader: ClientResponseReader[List[BankAccount]]): Future[List[BankAccount]] = {
    // create path and map variables
    val path = (addFmt("/api/bank-accounts"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getBankAccountUsingGET(id: Long)(implicit reader: ClientResponseReader[BankAccount]): Future[BankAccount] = {
    // create path and map variables
    val path = (addFmt("/api/bank-accounts/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def updateBankAccountUsingPUT(bankAccount: BankAccount)(implicit reader: ClientResponseReader[BankAccount], writer: RequestWriter[BankAccount]): Future[BankAccount] = {
    // create path and map variables
    val path = (addFmt("/api/bank-accounts"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (bankAccount == null) throw new Exception("Missing required parameter 'bankAccount' when calling BankAccountResourceApi->updateBankAccountUsingPUT")

    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, writer.write(bankAccount))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
