/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client

import java.text.SimpleDateFormat

import com.kodfarki.subscreasy.client.model.Company
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class CompanyResourceApi(
  val defBasePath: String = "https://localhost:8080",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new CompanyResourceApiAsyncHelper(client, config)

  /**
   * createCompany
   * 
   *
   * @param company company 
   * @return Company
   */
  def createCompanyUsingPOST(company: Company): Option[Company] = {
    val await = Try(Await.result(createCompanyUsingPOSTAsync(company), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * createCompany asynchronously
   * 
   *
   * @param company company 
   * @return Future(Company)
   */
  def createCompanyUsingPOSTAsync(company: Company): Future[Company] = {
      helper.createCompanyUsingPOST(company)
  }

  /**
   * deleteCompany
   * 
   *
   * @param id id 
   * @return void
   */
  def deleteCompanyUsingDELETE(id: Long) = {
    val await = Try(Await.result(deleteCompanyUsingDELETEAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * deleteCompany asynchronously
   * 
   *
   * @param id id 
   * @return Future(void)
   */
  def deleteCompanyUsingDELETEAsync(id: Long) = {
      helper.deleteCompanyUsingDELETE(id)
  }

  /**
   * getAllCompanies
   * 
   *
   * @return List[Company]
   */
  def getAllCompaniesUsingGET(): Option[List[Company]] = {
    val await = Try(Await.result(getAllCompaniesUsingGETAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getAllCompanies asynchronously
   * 
   *
   * @return Future(List[Company])
   */
  def getAllCompaniesUsingGETAsync(): Future[List[Company]] = {
      helper.getAllCompaniesUsingGET()
  }

  /**
   * getCompany
   * 
   *
   * @param id id 
   * @return Company
   */
  def getCompanyUsingGET(id: Long): Option[Company] = {
    val await = Try(Await.result(getCompanyUsingGETAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getCompany asynchronously
   * 
   *
   * @param id id 
   * @return Future(Company)
   */
  def getCompanyUsingGETAsync(id: Long): Future[Company] = {
      helper.getCompanyUsingGET(id)
  }

  /**
   * updateCompany
   * 
   *
   * @param company company 
   * @return Company
   */
  def updateCompanyUsingPUT(company: Company): Option[Company] = {
    val await = Try(Await.result(updateCompanyUsingPUTAsync(company), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * updateCompany asynchronously
   * 
   *
   * @param company company 
   * @return Future(Company)
   */
  def updateCompanyUsingPUTAsync(company: Company): Future[Company] = {
      helper.updateCompanyUsingPUT(company)
  }

}

class CompanyResourceApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def createCompanyUsingPOST(company: Company)(implicit reader: ClientResponseReader[Company], writer: RequestWriter[Company]): Future[Company] = {
    // create path and map variables
    val path = (addFmt("/api/companies"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (company == null) throw new Exception("Missing required parameter 'company' when calling CompanyResourceApi->createCompanyUsingPOST")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(company))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def deleteCompanyUsingDELETE(id: Long)(implicit reader: ClientResponseReader[Unit]): Future[Unit] = {
    // create path and map variables
    val path = (addFmt("/api/companies/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("DELETE", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getAllCompaniesUsingGET()(implicit reader: ClientResponseReader[List[Company]]): Future[List[Company]] = {
    // create path and map variables
    val path = (addFmt("/api/companies"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getCompanyUsingGET(id: Long)(implicit reader: ClientResponseReader[Company]): Future[Company] = {
    // create path and map variables
    val path = (addFmt("/api/companies/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def updateCompanyUsingPUT(company: Company)(implicit reader: ClientResponseReader[Company], writer: RequestWriter[Company]): Future[Company] = {
    // create path and map variables
    val path = (addFmt("/api/companies"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (company == null) throw new Exception("Missing required parameter 'company' when calling CompanyResourceApi->updateCompanyUsingPUT")

    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, writer.write(company))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
