/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client

import java.text.SimpleDateFormat

import com.kodfarki.subscreasy.client.model.MessageTemplate
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class MessageTemplateResourceApi(
  val defBasePath: String = "https://localhost:8080",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new MessageTemplateResourceApiAsyncHelper(client, config)

  /**
   * createMessageTemplate
   * 
   *
   * @param messageTemplate messageTemplate 
   * @return MessageTemplate
   */
  def createMessageTemplateUsingPOST(messageTemplate: MessageTemplate): Option[MessageTemplate] = {
    val await = Try(Await.result(createMessageTemplateUsingPOSTAsync(messageTemplate), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * createMessageTemplate asynchronously
   * 
   *
   * @param messageTemplate messageTemplate 
   * @return Future(MessageTemplate)
   */
  def createMessageTemplateUsingPOSTAsync(messageTemplate: MessageTemplate): Future[MessageTemplate] = {
      helper.createMessageTemplateUsingPOST(messageTemplate)
  }

  /**
   * deleteMessageTemplate
   * 
   *
   * @param id id 
   * @return void
   */
  def deleteMessageTemplateUsingDELETE(id: Long) = {
    val await = Try(Await.result(deleteMessageTemplateUsingDELETEAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * deleteMessageTemplate asynchronously
   * 
   *
   * @param id id 
   * @return Future(void)
   */
  def deleteMessageTemplateUsingDELETEAsync(id: Long) = {
      helper.deleteMessageTemplateUsingDELETE(id)
  }

  /**
   * getAllMessageTemplates
   * 
   *
   * @return List[MessageTemplate]
   */
  def getAllMessageTemplatesUsingGET(): Option[List[MessageTemplate]] = {
    val await = Try(Await.result(getAllMessageTemplatesUsingGETAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getAllMessageTemplates asynchronously
   * 
   *
   * @return Future(List[MessageTemplate])
   */
  def getAllMessageTemplatesUsingGETAsync(): Future[List[MessageTemplate]] = {
      helper.getAllMessageTemplatesUsingGET()
  }

  /**
   * getMessageTemplate
   * 
   *
   * @param id id 
   * @return MessageTemplate
   */
  def getMessageTemplateUsingGET1(id: Long): Option[MessageTemplate] = {
    val await = Try(Await.result(getMessageTemplateUsingGET1Async(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getMessageTemplate asynchronously
   * 
   *
   * @param id id 
   * @return Future(MessageTemplate)
   */
  def getMessageTemplateUsingGET1Async(id: Long): Future[MessageTemplate] = {
      helper.getMessageTemplateUsingGET1(id)
  }

  /**
   * updateMessageTemplate
   * 
   *
   * @param messageTemplate messageTemplate 
   * @return MessageTemplate
   */
  def updateMessageTemplateUsingPUT(messageTemplate: MessageTemplate): Option[MessageTemplate] = {
    val await = Try(Await.result(updateMessageTemplateUsingPUTAsync(messageTemplate), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * updateMessageTemplate asynchronously
   * 
   *
   * @param messageTemplate messageTemplate 
   * @return Future(MessageTemplate)
   */
  def updateMessageTemplateUsingPUTAsync(messageTemplate: MessageTemplate): Future[MessageTemplate] = {
      helper.updateMessageTemplateUsingPUT(messageTemplate)
  }

}

class MessageTemplateResourceApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def createMessageTemplateUsingPOST(messageTemplate: MessageTemplate)(implicit reader: ClientResponseReader[MessageTemplate], writer: RequestWriter[MessageTemplate]): Future[MessageTemplate] = {
    // create path and map variables
    val path = (addFmt("/api/message-templates"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (messageTemplate == null) throw new Exception("Missing required parameter 'messageTemplate' when calling MessageTemplateResourceApi->createMessageTemplateUsingPOST")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(messageTemplate))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def deleteMessageTemplateUsingDELETE(id: Long)(implicit reader: ClientResponseReader[Unit]): Future[Unit] = {
    // create path and map variables
    val path = (addFmt("/api/message-templates/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("DELETE", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getAllMessageTemplatesUsingGET()(implicit reader: ClientResponseReader[List[MessageTemplate]]): Future[List[MessageTemplate]] = {
    // create path and map variables
    val path = (addFmt("/api/message-templates"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getMessageTemplateUsingGET1(id: Long)(implicit reader: ClientResponseReader[MessageTemplate]): Future[MessageTemplate] = {
    // create path and map variables
    val path = (addFmt("/api/message-templates/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def updateMessageTemplateUsingPUT(messageTemplate: MessageTemplate)(implicit reader: ClientResponseReader[MessageTemplate], writer: RequestWriter[MessageTemplate]): Future[MessageTemplate] = {
    // create path and map variables
    val path = (addFmt("/api/message-templates"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (messageTemplate == null) throw new Exception("Missing required parameter 'messageTemplate' when calling MessageTemplateResourceApi->updateMessageTemplateUsingPUT")

    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, writer.write(messageTemplate))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
