/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client

import java.text.SimpleDateFormat

import com.kodfarki.subscreasy.client.model.Offer
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class OfferResourceApi(
  val defBasePath: String = "https://localhost:8080",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new OfferResourceApiAsyncHelper(client, config)

  /**
   * createOffer
   * 
   *
   * @param offer offer 
   * @return Offer
   */
  def createOfferUsingPOST(offer: Offer): Option[Offer] = {
    val await = Try(Await.result(createOfferUsingPOSTAsync(offer), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * createOffer asynchronously
   * 
   *
   * @param offer offer 
   * @return Future(Offer)
   */
  def createOfferUsingPOSTAsync(offer: Offer): Future[Offer] = {
      helper.createOfferUsingPOST(offer)
  }

  /**
   * deleteOffer
   * 
   *
   * @param id id 
   * @return void
   */
  def deleteOfferUsingDELETE(id: Long) = {
    val await = Try(Await.result(deleteOfferUsingDELETEAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * deleteOffer asynchronously
   * 
   *
   * @param id id 
   * @return Future(void)
   */
  def deleteOfferUsingDELETEAsync(id: Long) = {
      helper.deleteOfferUsingDELETE(id)
  }

  /**
   * getAllOffers
   * 
   *
   * @return List[Offer]
   */
  def getAllOffersUsingGET(): Option[List[Offer]] = {
    val await = Try(Await.result(getAllOffersUsingGETAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getAllOffers asynchronously
   * 
   *
   * @return Future(List[Offer])
   */
  def getAllOffersUsingGETAsync(): Future[List[Offer]] = {
      helper.getAllOffersUsingGET()
  }

  /**
   * getOffer
   * 
   *
   * @param id id 
   * @return Offer
   */
  def getOfferUsingGET(id: Long): Option[Offer] = {
    val await = Try(Await.result(getOfferUsingGETAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getOffer asynchronously
   * 
   *
   * @param id id 
   * @return Future(Offer)
   */
  def getOfferUsingGETAsync(id: Long): Future[Offer] = {
      helper.getOfferUsingGET(id)
  }

  /**
   * updateOffer
   * 
   *
   * @param offer offer 
   * @return Offer
   */
  def updateOfferUsingPUT(offer: Offer): Option[Offer] = {
    val await = Try(Await.result(updateOfferUsingPUTAsync(offer), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * updateOffer asynchronously
   * 
   *
   * @param offer offer 
   * @return Future(Offer)
   */
  def updateOfferUsingPUTAsync(offer: Offer): Future[Offer] = {
      helper.updateOfferUsingPUT(offer)
  }

}

class OfferResourceApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def createOfferUsingPOST(offer: Offer)(implicit reader: ClientResponseReader[Offer], writer: RequestWriter[Offer]): Future[Offer] = {
    // create path and map variables
    val path = (addFmt("/api/offers"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (offer == null) throw new Exception("Missing required parameter 'offer' when calling OfferResourceApi->createOfferUsingPOST")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(offer))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def deleteOfferUsingDELETE(id: Long)(implicit reader: ClientResponseReader[Unit]): Future[Unit] = {
    // create path and map variables
    val path = (addFmt("/api/offers/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("DELETE", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getAllOffersUsingGET()(implicit reader: ClientResponseReader[List[Offer]]): Future[List[Offer]] = {
    // create path and map variables
    val path = (addFmt("/api/offers"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getOfferUsingGET(id: Long)(implicit reader: ClientResponseReader[Offer]): Future[Offer] = {
    // create path and map variables
    val path = (addFmt("/api/offers/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def updateOfferUsingPUT(offer: Offer)(implicit reader: ClientResponseReader[Offer], writer: RequestWriter[Offer]): Future[Offer] = {
    // create path and map variables
    val path = (addFmt("/api/offers"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (offer == null) throw new Exception("Missing required parameter 'offer' when calling OfferResourceApi->updateOfferUsingPUT")

    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, writer.write(offer))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
