/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client

import java.text.SimpleDateFormat

import com.kodfarki.subscreasy.client.model.CreateOrderRequest
import com.kodfarki.subscreasy.client.model.Order
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class OrderResourceApi(
  val defBasePath: String = "https://localhost:8080",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new OrderResourceApiAsyncHelper(client, config)

  /**
   * createOrder
   * 
   *
   * @param orderRequest orderRequest 
   * @return Order
   */
  def createOrderUsingPOST(orderRequest: CreateOrderRequest): Option[Order] = {
    val await = Try(Await.result(createOrderUsingPOSTAsync(orderRequest), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * createOrder asynchronously
   * 
   *
   * @param orderRequest orderRequest 
   * @return Future(Order)
   */
  def createOrderUsingPOSTAsync(orderRequest: CreateOrderRequest): Future[Order] = {
      helper.createOrderUsingPOST(orderRequest)
  }

  /**
   * getAllOrders
   * 
   *
   * @return List[Order]
   */
  def getAllOrdersUsingGET(): Option[List[Order]] = {
    val await = Try(Await.result(getAllOrdersUsingGETAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getAllOrders asynchronously
   * 
   *
   * @return Future(List[Order])
   */
  def getAllOrdersUsingGETAsync(): Future[List[Order]] = {
      helper.getAllOrdersUsingGET()
  }

  /**
   * getOrder
   * 
   *
   * @param id id 
   * @return Order
   */
  def getOrderUsingGET(id: Long): Option[Order] = {
    val await = Try(Await.result(getOrderUsingGETAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getOrder asynchronously
   * 
   *
   * @param id id 
   * @return Future(Order)
   */
  def getOrderUsingGETAsync(id: Long): Future[Order] = {
      helper.getOrderUsingGET(id)
  }

  /**
   * updateOrder
   * 
   *
   * @param order order 
   * @return Order
   */
  def updateOrderUsingPUT(order: Order): Option[Order] = {
    val await = Try(Await.result(updateOrderUsingPUTAsync(order), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * updateOrder asynchronously
   * 
   *
   * @param order order 
   * @return Future(Order)
   */
  def updateOrderUsingPUTAsync(order: Order): Future[Order] = {
      helper.updateOrderUsingPUT(order)
  }

}

class OrderResourceApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def createOrderUsingPOST(orderRequest: CreateOrderRequest)(implicit reader: ClientResponseReader[Order], writer: RequestWriter[CreateOrderRequest]): Future[Order] = {
    // create path and map variables
    val path = (addFmt("/api/orders"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (orderRequest == null) throw new Exception("Missing required parameter 'orderRequest' when calling OrderResourceApi->createOrderUsingPOST")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(orderRequest))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getAllOrdersUsingGET()(implicit reader: ClientResponseReader[List[Order]]): Future[List[Order]] = {
    // create path and map variables
    val path = (addFmt("/api/orders"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getOrderUsingGET(id: Long)(implicit reader: ClientResponseReader[Order]): Future[Order] = {
    // create path and map variables
    val path = (addFmt("/api/orders/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def updateOrderUsingPUT(order: Order)(implicit reader: ClientResponseReader[Order], writer: RequestWriter[Order]): Future[Order] = {
    // create path and map variables
    val path = (addFmt("/api/orders"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (order == null) throw new Exception("Missing required parameter 'order' when calling OrderResourceApi->updateOrderUsingPUT")

    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, writer.write(order))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
