/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client

import java.text.SimpleDateFormat

import com.kodfarki.subscreasy.client.model.ServiceOffering
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class ServiceOfferingResourceApi(
  val defBasePath: String = "https://localhost:8080",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new ServiceOfferingResourceApiAsyncHelper(client, config)

  /**
   * createServiceOffering
   * 
   *
   * @param serviceOffering serviceOffering 
   * @return ServiceOffering
   */
  def createServiceOfferingUsingPOST(serviceOffering: ServiceOffering): Option[ServiceOffering] = {
    val await = Try(Await.result(createServiceOfferingUsingPOSTAsync(serviceOffering), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * createServiceOffering asynchronously
   * 
   *
   * @param serviceOffering serviceOffering 
   * @return Future(ServiceOffering)
   */
  def createServiceOfferingUsingPOSTAsync(serviceOffering: ServiceOffering): Future[ServiceOffering] = {
      helper.createServiceOfferingUsingPOST(serviceOffering)
  }

  /**
   * deleteServiceOffering
   * 
   *
   * @param id id 
   * @return void
   */
  def deleteServiceOfferingUsingDELETE(id: Long) = {
    val await = Try(Await.result(deleteServiceOfferingUsingDELETEAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * deleteServiceOffering asynchronously
   * 
   *
   * @param id id 
   * @return Future(void)
   */
  def deleteServiceOfferingUsingDELETEAsync(id: Long) = {
      helper.deleteServiceOfferingUsingDELETE(id)
  }

  /**
   * getAllServiceOfferings
   * 
   *
   * @return List[ServiceOffering]
   */
  def getAllServiceOfferingsUsingGET(): Option[List[ServiceOffering]] = {
    val await = Try(Await.result(getAllServiceOfferingsUsingGETAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getAllServiceOfferings asynchronously
   * 
   *
   * @return Future(List[ServiceOffering])
   */
  def getAllServiceOfferingsUsingGETAsync(): Future[List[ServiceOffering]] = {
      helper.getAllServiceOfferingsUsingGET()
  }

  /**
   * getServiceOffering
   * 
   *
   * @param id id 
   * @return ServiceOffering
   */
  def getServiceOfferingUsingGET(id: Long): Option[ServiceOffering] = {
    val await = Try(Await.result(getServiceOfferingUsingGETAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getServiceOffering asynchronously
   * 
   *
   * @param id id 
   * @return Future(ServiceOffering)
   */
  def getServiceOfferingUsingGETAsync(id: Long): Future[ServiceOffering] = {
      helper.getServiceOfferingUsingGET(id)
  }

  /**
   * updateServiceOffering
   * 
   *
   * @param serviceOffering serviceOffering 
   * @return ServiceOffering
   */
  def updateServiceOfferingUsingPUT(serviceOffering: ServiceOffering): Option[ServiceOffering] = {
    val await = Try(Await.result(updateServiceOfferingUsingPUTAsync(serviceOffering), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * updateServiceOffering asynchronously
   * 
   *
   * @param serviceOffering serviceOffering 
   * @return Future(ServiceOffering)
   */
  def updateServiceOfferingUsingPUTAsync(serviceOffering: ServiceOffering): Future[ServiceOffering] = {
      helper.updateServiceOfferingUsingPUT(serviceOffering)
  }

}

class ServiceOfferingResourceApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def createServiceOfferingUsingPOST(serviceOffering: ServiceOffering)(implicit reader: ClientResponseReader[ServiceOffering], writer: RequestWriter[ServiceOffering]): Future[ServiceOffering] = {
    // create path and map variables
    val path = (addFmt("/api/service-offerings"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (serviceOffering == null) throw new Exception("Missing required parameter 'serviceOffering' when calling ServiceOfferingResourceApi->createServiceOfferingUsingPOST")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(serviceOffering))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def deleteServiceOfferingUsingDELETE(id: Long)(implicit reader: ClientResponseReader[Unit]): Future[Unit] = {
    // create path and map variables
    val path = (addFmt("/api/service-offerings/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("DELETE", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getAllServiceOfferingsUsingGET()(implicit reader: ClientResponseReader[List[ServiceOffering]]): Future[List[ServiceOffering]] = {
    // create path and map variables
    val path = (addFmt("/api/service-offerings"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getServiceOfferingUsingGET(id: Long)(implicit reader: ClientResponseReader[ServiceOffering]): Future[ServiceOffering] = {
    // create path and map variables
    val path = (addFmt("/api/service-offerings/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def updateServiceOfferingUsingPUT(serviceOffering: ServiceOffering)(implicit reader: ClientResponseReader[ServiceOffering], writer: RequestWriter[ServiceOffering]): Future[ServiceOffering] = {
    // create path and map variables
    val path = (addFmt("/api/service-offerings"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (serviceOffering == null) throw new Exception("Missing required parameter 'serviceOffering' when calling ServiceOfferingResourceApi->updateServiceOfferingUsingPUT")

    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, writer.write(serviceOffering))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
