/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client

import java.text.SimpleDateFormat

import com.kodfarki.subscreasy.client.model.ServiceInstance
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class ServiceInstanceResourceApi(
  val defBasePath: String = "https://localhost:8080",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new ServiceInstanceResourceApiAsyncHelper(client, config)

  /**
   * createServiceInstance
   * 
   *
   * @param serviceInstance serviceInstance 
   * @return ServiceInstance
   */
  def createServiceInstanceUsingPOST(serviceInstance: ServiceInstance): Option[ServiceInstance] = {
    val await = Try(Await.result(createServiceInstanceUsingPOSTAsync(serviceInstance), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * createServiceInstance asynchronously
   * 
   *
   * @param serviceInstance serviceInstance 
   * @return Future(ServiceInstance)
   */
  def createServiceInstanceUsingPOSTAsync(serviceInstance: ServiceInstance): Future[ServiceInstance] = {
      helper.createServiceInstanceUsingPOST(serviceInstance)
  }

  /**
   * deleteServiceInstance
   * 
   *
   * @param id id 
   * @return void
   */
  def deleteServiceInstanceUsingDELETE(id: Long) = {
    val await = Try(Await.result(deleteServiceInstanceUsingDELETEAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * deleteServiceInstance asynchronously
   * 
   *
   * @param id id 
   * @return Future(void)
   */
  def deleteServiceInstanceUsingDELETEAsync(id: Long) = {
      helper.deleteServiceInstanceUsingDELETE(id)
  }

  /**
   * getAllServiceInstances
   * 
   *
   * @return List[ServiceInstance]
   */
  def getAllServiceInstancesUsingGET(): Option[List[ServiceInstance]] = {
    val await = Try(Await.result(getAllServiceInstancesUsingGETAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getAllServiceInstances asynchronously
   * 
   *
   * @return Future(List[ServiceInstance])
   */
  def getAllServiceInstancesUsingGETAsync(): Future[List[ServiceInstance]] = {
      helper.getAllServiceInstancesUsingGET()
  }

  /**
   * getServiceInstance
   * 
   *
   * @param id id 
   * @return ServiceInstance
   */
  def getServiceInstanceUsingGET(id: Long): Option[ServiceInstance] = {
    val await = Try(Await.result(getServiceInstanceUsingGETAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getServiceInstance asynchronously
   * 
   *
   * @param id id 
   * @return Future(ServiceInstance)
   */
  def getServiceInstanceUsingGETAsync(id: Long): Future[ServiceInstance] = {
      helper.getServiceInstanceUsingGET(id)
  }

  /**
   * updateServiceInstance
   * 
   *
   * @param serviceInstance serviceInstance 
   * @return ServiceInstance
   */
  def updateServiceInstanceUsingPUT(serviceInstance: ServiceInstance): Option[ServiceInstance] = {
    val await = Try(Await.result(updateServiceInstanceUsingPUTAsync(serviceInstance), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * updateServiceInstance asynchronously
   * 
   *
   * @param serviceInstance serviceInstance 
   * @return Future(ServiceInstance)
   */
  def updateServiceInstanceUsingPUTAsync(serviceInstance: ServiceInstance): Future[ServiceInstance] = {
      helper.updateServiceInstanceUsingPUT(serviceInstance)
  }

}

class ServiceInstanceResourceApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def createServiceInstanceUsingPOST(serviceInstance: ServiceInstance)(implicit reader: ClientResponseReader[ServiceInstance], writer: RequestWriter[ServiceInstance]): Future[ServiceInstance] = {
    // create path and map variables
    val path = (addFmt("/api/service-instances"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (serviceInstance == null) throw new Exception("Missing required parameter 'serviceInstance' when calling ServiceInstanceResourceApi->createServiceInstanceUsingPOST")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(serviceInstance))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def deleteServiceInstanceUsingDELETE(id: Long)(implicit reader: ClientResponseReader[Unit]): Future[Unit] = {
    // create path and map variables
    val path = (addFmt("/api/service-instances/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("DELETE", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getAllServiceInstancesUsingGET()(implicit reader: ClientResponseReader[List[ServiceInstance]]): Future[List[ServiceInstance]] = {
    // create path and map variables
    val path = (addFmt("/api/service-instances"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getServiceInstanceUsingGET(id: Long)(implicit reader: ClientResponseReader[ServiceInstance]): Future[ServiceInstance] = {
    // create path and map variables
    val path = (addFmt("/api/service-instances/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def updateServiceInstanceUsingPUT(serviceInstance: ServiceInstance)(implicit reader: ClientResponseReader[ServiceInstance], writer: RequestWriter[ServiceInstance]): Future[ServiceInstance] = {
    // create path and map variables
    val path = (addFmt("/api/service-instances"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (serviceInstance == null) throw new Exception("Missing required parameter 'serviceInstance' when calling ServiceInstanceResourceApi->updateServiceInstanceUsingPUT")

    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, writer.write(serviceInstance))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
