/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client

import java.text.SimpleDateFormat

import com.kodfarki.subscreasy.client.model.UsageNotification
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class UsageNotificationResourceApi(
  val defBasePath: String = "https://localhost:8080",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new UsageNotificationResourceApiAsyncHelper(client, config)

  /**
   * createUsageNotification
   * 
   *
   * @param usageNotification usageNotification 
   * @return UsageNotification
   */
  def createUsageNotificationUsingPOST(usageNotification: UsageNotification): Option[UsageNotification] = {
    val await = Try(Await.result(createUsageNotificationUsingPOSTAsync(usageNotification), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * createUsageNotification asynchronously
   * 
   *
   * @param usageNotification usageNotification 
   * @return Future(UsageNotification)
   */
  def createUsageNotificationUsingPOSTAsync(usageNotification: UsageNotification): Future[UsageNotification] = {
      helper.createUsageNotificationUsingPOST(usageNotification)
  }

  /**
   * deleteUsageNotification
   * 
   *
   * @param id id 
   * @return void
   */
  def deleteUsageNotificationUsingDELETE(id: Long) = {
    val await = Try(Await.result(deleteUsageNotificationUsingDELETEAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * deleteUsageNotification asynchronously
   * 
   *
   * @param id id 
   * @return Future(void)
   */
  def deleteUsageNotificationUsingDELETEAsync(id: Long) = {
      helper.deleteUsageNotificationUsingDELETE(id)
  }

  /**
   * getAllUsageNotifications
   * 
   *
   * @return List[UsageNotification]
   */
  def getAllUsageNotificationsUsingGET(): Option[List[UsageNotification]] = {
    val await = Try(Await.result(getAllUsageNotificationsUsingGETAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getAllUsageNotifications asynchronously
   * 
   *
   * @return Future(List[UsageNotification])
   */
  def getAllUsageNotificationsUsingGETAsync(): Future[List[UsageNotification]] = {
      helper.getAllUsageNotificationsUsingGET()
  }

  /**
   * getUsageNotification
   * 
   *
   * @param id id 
   * @return UsageNotification
   */
  def getUsageNotificationUsingGET(id: Long): Option[UsageNotification] = {
    val await = Try(Await.result(getUsageNotificationUsingGETAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * getUsageNotification asynchronously
   * 
   *
   * @param id id 
   * @return Future(UsageNotification)
   */
  def getUsageNotificationUsingGETAsync(id: Long): Future[UsageNotification] = {
      helper.getUsageNotificationUsingGET(id)
  }

  /**
   * updateUsageNotification
   * 
   *
   * @param usageNotification usageNotification 
   * @return UsageNotification
   */
  def updateUsageNotificationUsingPUT(usageNotification: UsageNotification): Option[UsageNotification] = {
    val await = Try(Await.result(updateUsageNotificationUsingPUTAsync(usageNotification), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * updateUsageNotification asynchronously
   * 
   *
   * @param usageNotification usageNotification 
   * @return Future(UsageNotification)
   */
  def updateUsageNotificationUsingPUTAsync(usageNotification: UsageNotification): Future[UsageNotification] = {
      helper.updateUsageNotificationUsingPUT(usageNotification)
  }

}

class UsageNotificationResourceApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def createUsageNotificationUsingPOST(usageNotification: UsageNotification)(implicit reader: ClientResponseReader[UsageNotification], writer: RequestWriter[UsageNotification]): Future[UsageNotification] = {
    // create path and map variables
    val path = (addFmt("/api/usage-notifications"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (usageNotification == null) throw new Exception("Missing required parameter 'usageNotification' when calling UsageNotificationResourceApi->createUsageNotificationUsingPOST")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(usageNotification))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def deleteUsageNotificationUsingDELETE(id: Long)(implicit reader: ClientResponseReader[Unit]): Future[Unit] = {
    // create path and map variables
    val path = (addFmt("/api/usage-notifications/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("DELETE", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getAllUsageNotificationsUsingGET()(implicit reader: ClientResponseReader[List[UsageNotification]]): Future[List[UsageNotification]] = {
    // create path and map variables
    val path = (addFmt("/api/usage-notifications"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getUsageNotificationUsingGET(id: Long)(implicit reader: ClientResponseReader[UsageNotification]): Future[UsageNotification] = {
    // create path and map variables
    val path = (addFmt("/api/usage-notifications/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def updateUsageNotificationUsingPUT(usageNotification: UsageNotification)(implicit reader: ClientResponseReader[UsageNotification], writer: RequestWriter[UsageNotification]): Future[UsageNotification] = {
    // create path and map variables
    val path = (addFmt("/api/usage-notifications"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (usageNotification == null) throw new Exception("Missing required parameter 'usageNotification' when calling UsageNotificationResourceApi->updateUsageNotificationUsingPUT")

    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, writer.write(usageNotification))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
