/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class Address (
  city: Option[String] = None,
  country: Option[String] = None,
  id: Option[Long] = None,
  name: Option[String] = None,
  postalCode: Option[String] = None,
  stateProvince: Option[String] = None,
  streetAddress: Option[String] = None
)

