/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class BankAccount (
  branch: Option[String] = None,
  city: Option[String] = None,
  company: Option[Company] = None,
  country: Option[String] = None,
  iban: String,
  id: Option[Long] = None,
  name: String
)

