/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class CompanyProps (
  apiKey: Option[String] = None,
  callbackUrl: Option[String] = None,
  company: Option[Company] = None,
  id: Option[Long] = None,
  paymentGateway: Option[String] = None,
  paymentGatewayApiKey: Option[String] = None,
  paymentGatewaySecurityKey: Option[String] = None,
  paytrMerchantId: Option[Integer] = None,
  payuMerchantKeyRenewals: Option[String] = None,
  payuSecretKeyRenewals: Option[String] = None,
  privacyPolicyUrl: Option[String] = None,
  secureKey: Option[String] = None
)

