/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class DeductionResult (
  capacity: Option[Number] = None,
  consumedResourceId: Option[Long] = None,
  overUsage: Option[Number] = None,
  requestedAmount: Option[Long] = None,
  subscriptionId: Option[Long] = None,
  usage: Option[Number] = None
)

