/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model

import java.util.Date

case class Deduction (
  amount: Option[Long] = None,
  id: Option[Long] = None,
  serviceId: Option[Long] = None,
  usageEndTime: Option[Date] = None,
  usageStartTime: Option[Date] = None,
  userId: Option[String] = None
)

