/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class MessageTemplate (
  company: Company,
  enabled: Option[Boolean] = None,
  eventType: Option[String] = None,
  id: Option[Long] = None,
  messageTemplate: Option[String] = None,
  notificationType: Option[String] = None,
  sender: Option[String] = None,
  subject: Option[String] = None
)

