/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class Offer (
  company: Company,
  id: Option[Long] = None,
  name: String,
  openEnded: Boolean,
  price: Number,
  recurrence: RecurrencePeriod,
  recurrenceCount: Option[Integer] = None,
  secureId: Option[String] = None,
  trialPeriod: Option[Integer] = None
)

