/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class Product (
  company: Company,
  description: String,
  id: Option[Long] = None,
  name: String,
  offers: Option[List[Offer]] = None,
  productType: Option[String] = None
)

