/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class SavedCard (
  binNumber: Option[String] = None,
  cardAlias: Option[String] = None,
  cardAssociation: Option[String] = None,
  cardBankCode: Option[Long] = None,
  cardBankName: Option[String] = None,
  cardFamily: Option[String] = None,
  cardToken: Option[String] = None,
  cardUserKey: Option[String] = None,
  cartType: Option[String] = None,
  id: Option[Long] = None
)

