/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model

import java.util.Date

case class ServiceInstance (
  currentUsage: Option[Number] = None,
  endDate: Option[Date] = None,
  id: Option[Long] = None,
  name: Option[String] = None,
  numberOfUnits: Option[Integer] = None,
  offer: Option[Offer] = None,
  overUsage: Option[Number] = None,
  overUsageQuota: Option[Number] = None,
  quotaOrigin: Option[String] = None,
  serviceOffering: Option[ServiceOffering] = None,
  startDate: Option[Date] = None,
  status: Option[String] = None,
  subscriberId: Option[String] = None,
  subscription: Option[Subsription] = None,
  `type`: Option[String] = None,
  version: Option[Long] = None
)

