/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class ServiceOffering (
  company: Option[Company] = None,
  description: Option[String] = None,
  id: Option[Long] = None,
  offer: Offer,
  overUsagePrice: Option[Number] = None,
  overUsageQuota: Option[Number] = None,
  price: Option[Number] = None,
  quotaAmount: Number,
  service: Option[Service] = None,
  unitName: Option[String] = None
)

