/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class ServiceOfferingResult (
  capacity: Option[String] = None,
  id: Option[Long] = None,
  name: Option[String] = None,
  price: Option[Number] = None,
  `type`: Option[String] = None,
  unitName: Option[String] = None,
  unitsPerPrice: Option[Number] = None
)

