/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model

import java.util.Date

case class ServiceInstanceResult (
  capacity: Option[Number] = None,
  endDate: Option[Date] = None,
  id: Option[Long] = None,
  name: Option[String] = None,
  overUsage: Option[Number] = None,
  `type`: Option[String] = None,
  usage: Option[Number] = None
)

