/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class StartSubscriptionRequest (
  callbackUrl: Option[String] = None,
  companySiteName: Option[String] = None,
  couponCode: Option[String] = None,
  editable: Option[Boolean] = None,
  offer: Option[Offer] = None,
  paymentCard: Option[PaymentCard] = None,
  paymentType: Option[String] = None,
  price: Option[Number] = None,
  privacyPolicyUrl: Option[Boolean] = None,
  subscriber: Option[Subscriber] = None
)

