/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model

import java.util.Date

case class Subscriber (
  billingAddress: Option[Address] = None,
  company: Option[Company] = None,
  createDate: Option[Date] = None,
  email: Option[String] = None,
  id: Option[Long] = None,
  identificationNo: Option[String] = None,
  name: Option[String] = None,
  phoneNumber: Option[String] = None,
  secureId: Option[String] = None,
  shippingAddress: Option[Address] = None,
  surname: Option[String] = None,
  taxNumber: Option[String] = None,
  worksFor: Option[String] = None
)

