/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class Subscriber (
  address: Option[String] = None,
  city: Option[String] = None,
  country: Option[String] = None,
  email: Option[String] = None,
  gsmNumber: Option[String] = None,
  identityNumber: Option[String] = None,
  ip: Option[String] = None,
  lastLoginDate: Option[String] = None,
  name: Option[String] = None,
  registrationDate: Option[String] = None,
  secureId: Option[String] = None,
  shippingAddress: Option[String] = None,
  shippingCity: Option[String] = None,
  shippingCountry: Option[String] = None,
  shippingName: Option[String] = None,
  shippingZipCode: Option[String] = None,
  surname: Option[String] = None,
  useBillingAddressForShipping: Option[Boolean] = None,
  zipCode: Option[String] = None
)

