/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model

import java.util.Date

case class Subsription (
  appliedCoupon: Option[Coupon] = None,
  cancelDate: Option[Date] = None,
  card: Option[SavedCard] = None,
  company: Company,
  endDate: Option[Date] = None,
  id: Option[Long] = None,
  lastEvent: Option[String] = None,
  offer: Offer,
  paymentMethod: Option[String] = None,
  services: Option[List[ServiceInstance]] = None,
  startDate: Option[Date] = None,
  status: Option[String] = None,
  subscriber: Option[Subscriber] = None,
  subscriberSecureId: Option[String] = None,
  termEndDate: Option[Date] = None,
  termStartDate: Option[Date] = None,
  trialEndDate: Option[Date] = None
)

