/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class WebHook (
  authenticationKey: Option[String] = None,
  company: Option[Company] = None,
  id: Option[Long] = None,
  paymentUpdated: Option[Boolean] = None,
  serverUrl: Option[String] = None,
  subscriberCreated: Option[Boolean] = None,
  subscriberUpdated: Option[Boolean] = None,
  subscriptionCreated: Option[Boolean] = None,
  subscriptionEnded: Option[Boolean] = None,
  subscriptionReactivated: Option[Boolean] = None,
  subscriptionRenewalFailed: Option[Boolean] = None,
  subscriptionRenewed: Option[Boolean] = None
)

