/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kodfarki.subscreasy.client.model


case class WebHookRequest (
  paymentLog: Option[ChargingLog] = None,
  savedCard: Option[SavedCard] = None,
  subscriber: Option[Subscriber] = None,
  subscription: Option[Subsription] = None,
  txId: Option[String] = None
)

